module.exports.ERRORS = {
  FAIL: {code: 'FAIL', message: 'Fail'},
  VERSION_NOT_EXIST: {code: 'VERSION_NOT_EXIST', message: 'Version not exist'},
  MODULE_NOT_EXIST: {code: 'MODULE_NOT_EXIST', message: 'Module not exist'},
  METHOD_NOT_EXIST: {code: 'METHOD_NOT_EXIST', message: 'Method not exist'},
  REQUIRED_PARAM_NOT_FOUND: {code: 'REQUIRED_PARAM_NOT_FOUND', message: 'Required param not found'},
  PARAM_WRONG_TYPE: {code: 'PARAM_WRONG_TYPE', message: 'Param wrong type'},
  PARAM_PICK_OF_TEST_FAIL: {code: 'PARAM_PICK_OF_TEST_FAIL', message: 'Parameter failed selection test'},
  OUT_OF_DIAPASON: {code: 'OUT_OF_DIAPASON', message: 'Param out of diapason'},
  ONLY_METHOD: {code: 'ONLY_METHOD', message: 'ONLY_METHOD'},
  PARAM_TOO_LONG: {code: 'PARAM_TOO_LONG', message: 'Param must be shorten'},
  PARAM_TOO_SHORT: {code: 'PARAM_TOO_SHORT', message: 'Param must be longer...'},
  REG_EXP_ERROR: {code: 'REG_EXP_ERROR', message: 'Param failed test'},
  NOT_MD5: {code: 'NOT_MD5', message: 'Expected md5'},
  UNKNOWN: {code: 'UNKNOWN', message: 'Unknown error'},
  SAME_LOGIN: {code: 'SAME_LOGIN', message: 'This login already exists'},
  API_CONNECT_ERROR: {code: 'API_CONNECT_ERROR', message: 'API_CONNECT_ERROR'},
  PERMISSION_DENIED: {code: 'PERMISSION_DENIED', message: 'Auth data incorrect'},
  NEED_AUTH: {code: 'NEED_AUTH', message: 'Need auth'},
  IS_NOT_POSITIVE_NUMBER: {code: 'IS_NOT_POSITIVE_NUMBER', message: 'Param must be positive (x > 0)'},
};