module.exports.ERRORS = {
  FAIL: {code: 'FAIL', message: 'Fail'},
  VERSION_NOT_EXIST: {code: 'VERSION_NOT_EXIST', message: 'Version not exist'},
  MODULE_NOT_EXIST: {code: 'MODULE_NOT_EXIST', message: 'Module not exist'},
  METHOD_NOT_EXIST: {code: 'METHOD_NOT_EXIST', message: 'Method not exist'},
  REQUIRED_PARAM_NOT_FOUND: {code: 'REQUIRED_PARAM_NOT_FOUND', message: 'Required param not found'},
  PARAM_WRONG_TYPE: {code: 'PARAM_WRONG_TYPE', message: 'Param wrong type'},
  PARAM_PICK_OF_TEST_FAIL: {code: 'PARAM_PICK_OF_TEST_FAIL', message: 'Parameter failed selection test'},
  OUT_OF_DIAPASON: {code: 'OUT_OF_DIAPASON', message: 'Param out of diapason'},
  ONLY_METHOD: {code: 'ONLY_METHOD', message: 'ONLY_METHOD'},
  PARAM_TOO_LONG: {code: 'PARAM_TOO_LONG', message: 'Param must be shorten'},
  PARAM_TOO_SHORT: {code: 'PARAM_TOO_SHORT', message: 'Param must be longer...'},
  REG_EXP_ERROR: {code: 'REG_EXP_ERROR', message: 'Param failed test'},
  MIDDLEWARE_ERROR: {code: 'MIDDLEWARE_ERROR', message: 'Error middleware'},
};